# This CircleCI YAML file is responsible for running tests and linting the Local Instant Reload Add-on repo

version: 2.1

orbs:
    node: circleci/node@5.1

jobs:
    build:
        executor: node/default
        steps:
            - checkout
            - run:
                  name: Set NPM Token
                  command: |
                      echo "registry=https://registry.npmjs.org/" > ~/.npmrc
                      echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> ~/.npmrc
            - node/install:
                  install-yarn: true
            - node/install-packages:
                  pkg-manager: "yarn"
            - run:
                  name: Build Add-On
                  command: yarn build
            - run:
                  name: ESLint
                  command: yarn lint
            - run:
                  name: Integration/Unit Tests
                  command: yarn test
