# This CircleCI YAML file is responsible for running tests and linting the Local Instant Reload Add-on repo

version: 2.1

anchors:
  set_npm_token: &set_npm_token
    run:
      name: Set NPM Token
      command: |
        echo "registry=https://registry.npmjs.org/" > ~/.npmrc
        echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> ~/.npmrc

  install_yarn_deps: &install_yarn_deps
    run:
      name: Install Dependencies
      command: yarn install --immutable

  restore_yarn_cache: &restore_yarn_cache
    restore_cache:
      name: Restore Yarn Package Cache
      keys:
        - yarn-packages-v1-{{ arch }}-{{ checksum "yarn.lock" }}
        - yarn-packages-v1-{{ arch }}

  save_yarn_cache: &save_yarn_cache
    save_cache:
      name: Save Yarn Package Cache
      key: yarn-packages-v1-{{ arch }}-{{ checksum "yarn.lock" }}
      paths:
        - ./node_modules

  build: &build
    run:
      name: Build Add-On
      command: yarn build

  lint: &lint
    run:
      name: ESLint
      command: |
        yarn lint
  tests: &tests
    run:
      name: Integration/Unit Tests
      command: |
        yarn test
jobs:
  build:
    docker:
      - image: circleci/node:12.14-browsers
    steps:
      - checkout
      - *set_npm_token
      - *restore_yarn_cache
      - *install_yarn_deps
      - *save_yarn_cache
      - *build
      - *lint
      - *tests
